services:
  mup-service:
    build: ./backend/mup-gradjani
    container_name: mup-service
    env_file: ./backend/mup-gradjani/.env
    ports:
      - "8002:8002"
    depends_on:
      postgres:
        condition: service_healthy
        
  sso-service:
    build: ./backend/sso-auth
    container_name: sso-service
    env_file: ./backend/sso-auth/.env
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy

  zzs-service:
    build: ./backend/zzs-statistika
    container_name: zzs-service
    env_file: ./backend/zzs-statistika/.env
    ports:
      - "8003:8003"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: euprava
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d euprava"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:

networks:
  euprava-network:
    driver: bridge
